apiVersion: v1
kind: ConfigMap
metadata:
  name: restrogreen-config
  namespace: restrogreen
data:
  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_NAME: "restrogreen"
  DB_PORT: "3306"
  JWT_SECRET: "restrogreen_jwt_secret_key_2024"