// lib/pdfGenerator.js
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function generatePaymentSlip(orderData, paymentData) {
  const doc = new jsPDF();
  
  // Header with pastel green
  doc.setFillColor(200, 230, 201);
  doc.rect(0, 0, 210, 35, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(46, 125, 50);
  doc.text('RestroGreen', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(76, 76, 76);
  doc.text('Payment Receipt', 105, 30, { align: 'center' });
  
  // Restaurant info
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('RestroGreen Restaurant', 14, 45);
  doc.text('Date: ' + new Date(paymentData.created_at).toLocaleDateString(), 14, 50);
  doc.text('Slip No: ' + paymentData.id, 14, 55);
  
  // Order details
  doc.setFontSize(11);
  doc.setTextColor(46, 125, 50);
  doc.text('Order Details', 14, 65);
  
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text('Table Number: ' + orderData.table_number, 14, 72);
  doc.text('Order ID: ' + orderData.id, 14, 77);
  
  // Items table
  const tableColumn = ['Item', 'Qty', 'Price', 'Total'];
  const tableRows = orderData.items.map(item => [
    item.item_name,
    item.quantity,
    'Rs. ' + item.price.toFixed(2),
    'Rs. ' + (item.quantity * item.price).toFixed(2)
  ]);
  
  doc.autoTable({
    startY: 82,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [200, 230, 201],
      textColor: [46, 125, 50],
      fontStyle: 'bold'
    },
    styles: {
      fontSize: 9,
      cellPadding: 4
    }
  });
  
  const finalY = doc.lastAutoTable.finalY + 10;
  
  // Total
  doc.setFontSize(12);
  doc.setTextColor(46, 125, 50);
  doc.setFont(undefined, 'bold');
  doc.text('Total Amount: Rs. ' + paymentData.amount.toFixed(2), 150, finalY, { align: 'right' });
  
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.setFont(undefined, 'normal');
  doc.text('Payment Method: ' + paymentData.payment_method, 14, finalY + 8);
  doc.text('Generated by: Manager', 14, finalY + 14);
  
  // Footer
  doc.setFillColor(200, 230, 201);
  doc.rect(0, 275, 210, 22, 'F');
  doc.setFontSize(8);
  doc.setTextColor(76, 76, 76);
  doc.text('Thank you for dining with RestroGreen!', 105, 288, { align: 'center' });
  
  return doc;
}